app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000
  analytics:
    matomo:
      host: ${ANALYTICS_MATOMO_INSTANCE_URL}
      siteId: ${ANALYTICS_MATOMO_SITE_ID}

  redirects:
    rules:
      - type: entity
        from: component:default/dummy-component
        to: component:default/example-website-for-redirects-plugin
        message: Redirection test
      - type: entity
        from: component:default/dummy2
        to: /
        message: Redirection test
      - type: url
        from: /dummy-path
        to: /

organization:
  name: Backstage Plugins

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    default-src:
      - "'self'"
      - 'http:'
      - 'https:'
      - 'https://cdnapisec.kaltura.com/'
      - 'https://analytics.kaltura.com/'

    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
    script-src:
      [
        "'self'",
        "'unsafe-eval'",
        'https://${ANALYTICS_MATOMO_INSTANCE_URL}',
        '${JIRA_URL}',
      ]
    img-src: ["'self'", 'data:', '$JIRA_URL']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    client: better-sqlite3
    connection: ':memory:'
  cache:
    store: memory
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir
  auth:
    externalAccess:
      - type: static
        options:
          token: ${AUDIT_COMPLIANCE_ACCESS_TOKEN}
          subject: audit-compliance-token
        accessRestrictions:
          - plugin: audit-compliance

integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration
      token: ${GITHUB_TOKEN}
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token: ${GHE_TOKEN}
  gitlab:
    - host: gitlab.cee.redhat.com
      token: ${GITLAB_CEE_TOKEN}
      apiBaseUrl: https://gitlab.cee.redhat.com/api/v4
  servicenow:
    - host: ${SERVICE_NOW_HOST}
      apiBaseUrl: ${SERVICE_NOW_BASE_API_URL}
      credentials:
        username: ${SERVICE_NOW_USERNAME}
        password: ${SERVICE_NOW_PASSWORD}

proxy:
  ### Example for how to add a proxy endpoint for the frontend.
  ### A typical reason to do this is to handle HTTPS and CORS for internal services.
  endpoints:
    '/spaship':
      target: ${SPASHIP_API_URL}
      secure: false
      credentials: dangerously-allow-unauthenticated
      changeOrigin: true
      allowedMethods: ['GET']
      headers:
        Authorization: Bearer ${SPASHIP_API_TOKEN}
    '/cmdb':
      target: ${SERVICE_NOW_BASE_API_URL}
      changeOrigin: true
      allowedMethods: ['GET']
      headers:
        Authorization: ${SERVICE_NOW_API_TOKEN}
    '/lighthouse':
      target: ${LIGHTHOUSE_INSTANCE_URL}
      changeOrigin: true
      allowedMethods: ['GET']
    '/jira':
      target: ${JIRA_URL}
      credentials: dangerously-allow-unauthenticated
      headers:
        Authorization: Bearer ${JIRA_TOKEN}
        Accept: 'application/json'
        Content-Type: 'application/json'
        X-Atlassian-Token: 'no-check'
        User-Agent: 'Backstage-Jira-Plugin'
    '/docsbot':
      target: ${DOCSBOT_QUERY_STREAM_URL}
      credentials: dangerously-allow-unauthenticated
      changeOrigin: true
      allowedMethods: ['GET', 'POST']
    '/docsbotstats':
      target: ${DOCSBOT_STATS_URL}
      changeOrigin: true
      allowedMethods: ['GET']
    '/statuspage':
      target: ${STATUSPAGE_URL}
      headers:
        Authorization: ${STATUSPAGE_AUTH}
        Content-Type: 'application/json'
    '/hydrasupport':
      target: ${HYDRA_SUPPORT_DASHBOARD_CONFIG_URL}
      credentials: dangerously-allow-unauthenticated
      changeOrigin: true
      allowedMethods: ['GET']
    # '/mcp':
    #   target: ${MCP_SERVER_BASE_URL}
    #   headers:
    #     PRIVATE-TOKEN: ${MCP_SERVER_TOKEN}
    #     Content-Type: 'application/json'
    #   credentials: dangerously-allow-unauthenticated
    #   changeOrigin: true
    #   allowedMethods: ['GET', 'OPTIONS', 'PUT']
    #   secure: false

jira:
  proxyPath: /jira

lighthouse:
  instance_url: ${LIGHTHOUSE_INSTANCE_URL}
  contact_us: ${LIGHTHOUSE_CONTACT_URL}

spaship:
  managerHost: ${SPASHIP_MANAGER_URL}
  slackUrl: ${SPASHIP_SLACK_URL}
  contactMail: ${SPASHIP_MAIL}
  githubUrl: ${SPASHIP_GITHUB_URL}
  owner: ${SPASHIP_OWNER_REF}

matomo:
  apiToken: ${MATOMO_API_TOKEN}
  apiUrl: ${MATOMO_API_URL}
  frontendBaseUrl: ${MATOMO_INSTANCE_URL}
  contactUsLink: ${MATOMO_CONTACT_URL}
  secure: false

cmdb:
  host: ${SERVICE_NOW_BASE_API_URL}

docsbot:
  statsUrl: ${DOCSBOT_STATS_URL}

proxyManager:
  apiBaseUrl: ${PROXY_MANAGER_API_BASE_URL}

feedback:
  baseEntityRef: ${FEEDBACK_PLUGIN_BASE_ENTITY} # for global feedbacks
  summaryLimit: ${FEEDBACK_PLUGIN_SUMMARY_LIMIT}
  integrations:
    jira:
      - host: ${JIRA_URL}
        token: ${JIRA_TOKEN}

    email:
      host: ${EMAIL_HOST}
      port: ${EMAIL_PORT}
      from: ${EMAIL_FROM}
      secure: false # true if port is 465
      caCert: ${NODE_EXTRA_CA_CERTS}

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    guest: {}
    oauth2:
      development:
        authorizationUrl: ${AUTH_SSO_AUTHORIZATION_URL}
        tokenUrl: ${AUTH_SSO_TOKEN_URL}
        clientId: ${AUTH_SSO_CLIENT_ID}
        clientSecret: ${AUTH_SSO_CLIENT_SECRET}

scaffolder:
  {}
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  readonly: true
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow:
        - Component
        - System
        - API
        - Resource
        - Location
        - Workstream
        - Template
        - MCPServer
        - ART
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Test data for lighthouse plugin
    - type: file
      target: ../../examples/test-data/lighthouse-plugin.yaml
    # Test data for Matomo plugin
    - type: file
      target: ../../examples/test-data/matomo-plugin.yaml
    # Test data for SPAship plugin
    - type: file
      target: ../../examples/test-data/spaship-plugin.yaml
    # Test data for CMDB plugin
    - type: file
      target: ../../examples/test-data/cmdb-plugin.yaml
      rules:
        - allow: [Component, User]
    - type: file
      target: ../../examples/test-data/jira-server-plugin.yaml
    - type: file
      target: ../../examples/test-data/contact-details-plugin.yaml
      rules:
        - allow: [Component, User, Group]
    # Test data for Feedback plugin
    - type: file
      target: ../../examples/test-data/feedback-plugin.yaml

    # Test data for report portal
    - type: file
      target: ../../examples/test-data/report-portal-plugin.yaml
      rules:
        - allow:
            - Component
            - User

    - type: file
      target: ../../examples/test-data/enrichment-data.yaml
      rules:
        - allow:
            - Component
            - EnrichmentData
    # Local example template
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    # Local example workstream users data
    - type: file
      target: ../../examples/test-data/workstream-plugin.yaml
      rules:
        - allow: [User, Group]

    # Local example mcp server
    - type: file
      target: ../../examples/test-data/mcp-servers.yaml

    # Local example redirection target component
    - type: file
      target: ../../examples/test-data/redirects-plugin.yaml

    ## Uncomment these lines to add more example data
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    ## Uncomment these lines to add an example org
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
    #   rules:
    #     - allow: [User, Group]

permission:
  enabled: false
  rbac:
    plugins:
      workstream:
        permission:
          - workstream.create
          - workstream.update
          - workstream.delete
          - workstream.art.create
          - workstream.art.update
          - workstream.art.delete
        users:
          - name: group:development/guests
    admins:
      - name: user:redhat/yoswal
      - name: user:redhat/mdeshmuk
      - name: user:redhat/roommen

# Report portal plugin
reportPortal:
  supportEmail: ${REPORT_PORTAL_SUPPORT_EMAIL}
  integrations:
    - host: ${REPORT_PORTAL_HOST}
      baseUrl: ${REPORT_PORTAL_BASE_URL}
      token: ${REPORT_PORTAL_TOKEN}
      filterType: 'INTERNAL'

spotify:
  licenseKey: ${SPOTIFY_LICENSE_KEY}

soundcheck:
  collectors:
    gitlab:
      $include: ./soundcheck/collectors/gitlab.yaml
    sonarqube:
      $include: ./soundcheck/collectors/sonarqube.yaml
    redHatCore:
      $include: ./soundcheck/collectors/redHatCore.yaml
    redHatGitLab:
      $include: ./soundcheck/collectors/redHatGitLab.yaml
    redHatServiceNow:
      $include: ./soundcheck/collectors/redHatServiceNow.yaml
    redHatSmartsheet:
      $include: ./soundcheck/collectors/redHatSmartsheet.yaml
  checks:
    $include: ./soundcheck/checks/preprod.yaml
  programs:
    $include: ./soundcheck/programs/preprod.yaml
  remote_file_updates:
    disabled: false
    frequency:
      minutes: 5

dataLayer:
  splunkToken: ${SPLUNK_TOKEN}
  splunkApiHost: ${SPLUNK_API_HOST}
  splunkSubgraphsSnippet: ${SPLUNK_SUBGRAPHS_SNIPPET}
  schedule:
    frequency:
      hour: 6
    timeout:
      hours: 12

auditCompliance:
  roverUsername: ${ROVER_USERNAME}
  roverPassword: ${ROVER_PASSWORD}
  roverBaseUrl: ${ROVER_BASE_URL}
  gitlabToken: ${GITLAB_TOKEN}
  gitlabBaseUrl: ${GITLAB_BASE_URL}
  jiraUrl: ${JIRA_URL}
  jiraToken: ${JIRA_TOKEN}
  email:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    from: ${EMAIL_FROM}
    secure: false
    caCert: ${NODE_EXTRA_CA_CERTS}
